name: Compilar Transmisor Pico

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Descargar codigo
      uses: actions/checkout@v4

    - name: Instalar herramientas de compilacion
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake gcc-arm-none-eabi libnewlib-arm-none-eabi libstdc++-arm-none-eabi-newlib python3 wget unzip

    - name: Descargar SDK seguro sin Git
      run: |
        # Descarga el SDK empaquetado directo desde los servidores de Raspberry Pi
        wget https://github.com -O pico-sdk.zip
        unzip pico-sdk.zip
        mv pico-sdk-master /home/runner/pico-sdk
        
        # Descarga e inicializa submódulos requeridos (como tinyusb) de forma empaquetada
        cd /home/runner/pico-sdk
        wget https://github.com -O tinyusb.zip
        unzip tinyusb.zip
        mv tinyusb-master lib/tinyusb

    - name: Compilar Transmisor
      run: |
        export PICO_SDK_PATH=/home/runner/pico-sdk
        mkdir build && cd build
        cmake -DPICO_BOARD=pico ..
        cd 18_transmitter
        make
        
    - name: Guardar binario .uf2
      uses: actions/upload-artifact@v4
      with:
        name: executable-transmisor
        path: build/18_transmitter/**/*.uf2
