name: Compilar Transmisor Pico

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Descargar codigo
      uses: actions/checkout@v4

    - name: Instalar herramientas de compilacion
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake gcc-arm-none-eabi libnewlib-arm-none-eabi libstdc++-arm-none-eabi-newlib python3

    - name: Cargar SDK de Pico Preinstalado
      uses: EngineeringDesignResearch/pico-sdk-action@v2
      with:
        pico-sdk-version: '1.5.1' # Versión estable oficial

    - name: Compilar Transmisor
      run: |
        mkdir build && cd build
        cmake -DPICO_BOARD=pico ..
        cd 18_transmitter
        make
        
    - name: Guardar binario .uf2
      uses: actions/upload-artifact@v4
      with:
        name: executable-transmisor
        path: build/18_transmitter/**/*.uf2
