name: Compilar Transmisor Pico

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Descargar codigo
      uses: actions/checkout@v4

    - name: Instalar herramientas de compilacion
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake gcc-arm-none-eabi libnewlib-arm-none-eabi libstdc++-arm-none-eabi-newlib python3 wget unzip

    - name: Descargar SDK Usando la API de GitHub
      run: |
        # Evitamos escribir la URL: usamos la API de descargas de la Fundación Raspberry Pi
        wget "https://github.com" -O pico-sdk.zip
        unzip pico-sdk.zip -d /home/runner/pico-sdk-temp
        mv /home/runner/pico-sdk-temp/* /home/runner/pico-sdk

        # Descargamos TinyUSB de la misma forma segura
        wget "https://github.com" -O tinyusb.zip
        unzip tinyusb.zip -d /home/runner/tinyusb-temp
        mv /home/runner/tinyusb-temp/* /home/runner/pico-sdk/lib/tinyusb

    - name: Compilar Transmisor
      run: |
        export PICO_SDK_PATH=/home/runner/pico-sdk
        mkdir build && cd build
        cmake -DPICO_BOARD=pico ..
        cd 18_transmitter
        make
        
    - name: Guardar binario .uf2
      uses: actions/upload-artifact@v4
      with:
        name: executable-transmisor
        path: build/18_transmitter/**/*.uf2
